apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pumr3ecnm-nodejs
  janus-idp.io/tekton: pumr3ecnm-nodejs
  backstage.io/kubernetes-id: pumr3ecnm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pumr3ecnm-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
